name: "Setup pip-tools"
description: "Setup python and deps using pip-tools"

inputs:
  dependency-path:
    description: path to extra requirements
    required: false
    default: "backend/requirements.txt"
  sync:
    description: run pip-sync
    required: false
    default: true
  python-version:
    description: python version
    required: false
    default: "3.10"
  pip-version:
    description: pip version
    required: false
    default: "~=23.1.0"
  pip-tools-version:
    description: pip-tools version
    required: false
    default: "~=6.13.0"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache dependencies
      if: ${{ inputs.sync != 'false' }}
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: pip-${{ env.pythonLocation }}-${{ hashFiles(inputs.dependency-path) }}
        restore-keys: |
          pip-${{ env.pythonLocation }}-${{ hashFiles(inputs.dependency-path) }}
          pip-${{ env.pythonLocation }}-
    - run: pip install --disable-pip-version-check --upgrade "pip${{ inputs.pip-version }}" "pip-tools${{ inputs.pip-tools-version }}" wheel
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
    - run: pip-sync ${{ inputs.dependency-path }}
      if: ${{ inputs.sync != 'false' && steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
